version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  python: circleci/python@2.0.3
  node: circleci/node@5.0.2
jobs:
  deploy-to-staging:
    docker:
      - image: cimg/base:2022.05
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - heroku/install
      - heroku/push-docker-image:
          app-name: $HEROKU_STAGING_NAME
          process-types: web
      - heroku/release-docker-image:
          app-name: $HEROKU_STAGING_NAME
  test-frontend:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm install --prefix react-app
      - run:
          name: Run React Tests
          command: npm test --prefix react-app
  build-test-backend:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: pytest
          pkg-manager: pipenv
      - run:
          command: |
            pipenv run pytest --version
          name: Run tests
  run-playwright-tests:
    docker:
      - image: mcr.microsoft.com/playwright:v1.22.0-focal
    steps:
      - checkout
      - run: npm install
      - run: npx playwright install
      - run: npx playwright test
  deploy:
    docker:
      - image: cimg/base:2022.05
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - heroku/install
      - heroku/push-docker-image:
          app-name: $HEROKU_APP_NAME
          process-types: web
      - heroku/release-docker-image:
          app-name: $HEROKU_APP_NAME
workflows:
  test-and-deploy:
    jobs:
      - deploy-to-staging:
          filters:
            branches:
              only: main
      - test-frontend
      - build-test-backend
      - run-playwright-tests:
          filters:
            branches:
              only: main
          requires:
            - deploy-to-staging
            - test-frontend
            - build-test-backend
      - deploy:
          requires:
            - test-frontend
            - build-test-backend
            - run-playwright-tests
          filters:
            branches:
              only: main
