version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  python: circleci/python@2.0.3
  node: circleci/node@5.0.2
jobs:
  deploy-to-staging:
    machine: true
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/push-docker-image:
          app-name: $HEROKU_STAGING_NAME
  test-frontend:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm install --prefix react-app
      - run:
          name: Run React Tests
          command: npm test --prefix react-app
  build-test-backend:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: pytest
          pkg-manager: pipenv
      - run:
          command: |
            pipenv run pytest --version
          name: Run tests
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME} web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME} web
workflows:
  test-and-deploy:
    jobs:
      - deploy-to-staging
      - test-frontend
      - build-test-backend
      - deploy:
          requires:
            - test-frontend
            - build-test-backend
          filters:
            branches:
              only: main
