"""updated associations

Revision ID: ffdde997d22b
Revises: a160215dcc39
Create Date: 2021-03-11 21:09:41.304152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdde997d22b'
down_revision = 'a160215dcc39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_items', sa.Column('shopping_list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shopping_list_items', 'shopping_lists', ['shopping_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shopping_list_items_shopping_list_id_fkey', 'shopping_list_items', type_='foreignkey')
    op.drop_column('shopping_list_items', 'shopping_list_id')
    # ### end Alembic commands ###
