"""added categories

Revision ID: cca087112f71
Revises: 6341fe623cd3
Create Date: 2021-03-17 14:04:48.098347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca087112f71'
down_revision = '6341fe623cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categories', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.add_column('items', sa.Column(
        'category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'])
    op.drop_column('items', 'aisle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column(
        'aisle', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('items_category_id_fkey', 'items', type_='foreignkey')
    op.drop_column('items', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
