"""added in cart column to SLI

Revision ID: 25a56a861f95
Revises: cca087112f71
Create Date: 2021-03-22 14:13:08.702975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a56a861f95'
down_revision = 'cca087112f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_items', sa.Column(
        'in_cart', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list_items', 'in_cart')
    # ### end Alembic commands ###
