FROM python:3.8

WORKDIR /usr/src/app

ENV FLASK_APP=app
ENV FLASK_DEBUG=true
ENV SQLALCHEMY_ECHO=True

COPY . .
RUN pip install -r requirements.txt
RUN pip install psycopg2
# RUN flask db upgrade
# RUN flask seed all

EXPOSE 5000

CMD flask run
